-- Parse every staged PDF with Cortex, chunk it, and (re)build the search service.
-- Domain = filename prefix before "__", e.g. cpr__aha_guide.pdf -> cpr. No prefix -> general.
USE WAREHOUSE TEDDY_WH;
USE SCHEMA TEDDY.CORE;
ALTER STAGE DOCS REFRESH;

CREATE OR REPLACE TABLE DOC_CHUNKS AS
WITH parsed AS (
  SELECT RELATIVE_PATH AS FILE,
         SNOWFLAKE.CORTEX.PARSE_DOCUMENT(@DOCS, RELATIVE_PATH, {'mode': 'LAYOUT'}):content::STRING AS TEXT
  FROM DIRECTORY(@DOCS)
  WHERE RELATIVE_PATH ILIKE '%.pdf'
)
SELECT p.FILE,
       REPLACE(REGEXP_REPLACE(SPLIT_PART(p.FILE, '.', 1), '^.*__', ''), '_', ' ') AS TITLE,
       LOWER(IFF(CONTAINS(p.FILE, '__'), SPLIT_PART(p.FILE, '__', 1), 'general')) AS DOMAIN,
       c.VALUE::STRING AS CHUNK
FROM parsed p,
     LATERAL FLATTEN(SNOWFLAKE.CORTEX.SPLIT_TEXT_RECURSIVE_CHARACTER(p.TEXT, 'markdown', 1200, 150)) c;

CREATE OR REPLACE CORTEX SEARCH SERVICE DOCS_SEARCH
  ON CHUNK
  ATTRIBUTES DOMAIN, TITLE
  WAREHOUSE = TEDDY_WH
  TARGET_LAG = '1 day'
AS SELECT CHUNK, DOMAIN, TITLE, FILE FROM DOC_CHUNKS;
