-- Parse every staged PDF with AI_PARSE_DOCUMENT (LAYOUT), chunk 1500/200, build the DOC_SEARCH service.
-- Domain = filename prefix before "__", e.g. cpr__aha_guide.pdf -> cpr. No prefix -> general.
USE WAREHOUSE {WH};
USE SCHEMA TEDDY.CORE;
ALTER STAGE DOCS REFRESH;

CREATE OR REPLACE TABLE DOC_PAGES AS
SELECT RELATIVE_PATH AS FILE,
       AI_PARSE_DOCUMENT(TO_FILE('@TEDDY.CORE.DOCS', RELATIVE_PATH), {'mode': 'LAYOUT'}):content::STRING AS TEXT
FROM DIRECTORY(@DOCS)
WHERE RELATIVE_PATH ILIKE '%.pdf';

CREATE OR REPLACE TABLE DOC_CHUNKS AS
SELECT p.FILE,
       REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(p.FILE, '\\.pdf$', '', 1, 0, 'i'), '^.*__', ''), '_', ' ') AS TITLE,
       LOWER(IFF(CONTAINS(p.FILE, '__'), SPLIT_PART(p.FILE, '__', 1), 'general')) AS DOMAIN,
       c.INDEX AS CHUNK_NO,
       c.VALUE::STRING AS CHUNK
FROM DOC_PAGES p,
     LATERAL FLATTEN(SNOWFLAKE.CORTEX.SPLIT_TEXT_RECURSIVE_CHARACTER(p.TEXT, 'markdown', 1500, 200)) c;

CREATE OR REPLACE CORTEX SEARCH SERVICE DOC_SEARCH
  ON CHUNK
  ATTRIBUTES DOMAIN, TITLE
  WAREHOUSE = {WH}
  TARGET_LAG = '1 day'
AS SELECT CHUNK, DOMAIN, TITLE, FILE FROM DOC_CHUNKS;
